id: P87CEC9BA
initial_creation_type: ocr
source_metadata:
  volumes:
    c692b989a1da4a94af151bd3b661a8e0:
      base_file: v060.txt
      image_group_id: I1PD95905
      title: དབུ་མ་ལ་འཇུག་པ།
      total_pages: 1913
      volume_number: 60
